### ISSUE TITLE
"kicking the tires" issues

### ISSUE THREAD

**Issue by budparr** [daviddarnes/garth#1]
Hi David,
When I follow your instructions I get `jekyll 3.2.0.pre.beta1 | Error:  The garth-jekyll-theme theme could not be found.` so I added the following to the Gemfile

```
gem "jekyll", "3.2.0.pre.beta1"
group :jekyll_plugins do
  gem "garth-jekyll-theme"
  gem "jekyll-seo-tag"
  gem "jekyll-paginate"
end
```

and ran that. I'm still getting the default theme even though I see that your js and css files are being generated. 

If I delete my `_layouts` folder, I get what appears to be your theme, but it's pretty funky.

I did this on two separate installs. 

<img width="1440" alt="screen shot 2016-06-20 at 11 27 38 am" src="https://cloud.githubusercontent.com/assets/115347/16200164/23f1a1d2-36da-11e6-99bb-3a0b351d668c.png">

**Comment by daviddarnes** [comment]
You shouldn't have your `_layouts`, `_includes` or `_sass` folders in your own Jekyll site. Are you applying the layouts to pages and posts?

**Comment by budparr** [comment]
I just did a Jekyll new to start with. Wasn't clear to delete anything, but I changed the default main.scss to styles.scss, added the js folder (from your instructions), and then deleted the `_layouts` folder when I wasn't seeing the theme. When I deleted the `_includes` folder, I got build failures because an icon file (I don't remember which, I closed that terminal window) was missing.

**Comment by daviddarnes** [comment]
Gah, this theming setup isn't easy. Sorry @budparr, what logo are you using for the logo path? It needs to be a gravatar image path or github avatar path (another thing not stated in the readme).

**Comment by budparr** [comment]
Dunno. I didn't change anything. I never really use `jekyll new` so I'm not familiar with what's in there. Seems like you shouldn't have to do anything locally at all to drop in a theme - haven't really looked though.

**Comment by daviddarnes** [comment]
Still haven't looked at this properly. At the minute the dev version of Jekyll themes is really just code as assets. In other words, optionally include CSS, HTML includes and layouts from another preset source.

I'm not concerned about the design, it's the achievement I'm aiming for. A successful theme install will be a 👍  in my books, and will hopefully help the development of this awesome addition.

**Comment by budparr** [comment]
Agree, except a successful install probably shouldn't be one that requires the end-user to delete anything, don't you agree?

**Comment by daviddarnes** [comment]
@budparr are you referring to the logo issue? Because I'd agree, it would certainly remove complexity to it 😄

**Comment by budparr** [comment]
I mean having to delete the _layouts folder, and _includes folder. I suppose if a fresh install didn't come with those things it would make more sense. I'm just thinking of a new user who would run jekyll new and then want to use a theme.

**Comment by daviddarnes** [comment]
Hmm, I like that technique from a dev point of view. I could work with an initial theme and then overwrite the things I want to customise. However it doesn't help users with pre-existing Jekyll sites. That's how themes work though 😕 , maybe we should open up discussion on [talk.jekyllrb.com](https://talk.jekyllrb.com/)?

**Comment by budparr** [comment]
I see from the docs (first time looking at them), that it's intentional so that a user can override theme defaults. So, I suppose the only thing that really needs to change is the default Jekyll install, because anyone with a pre-existing instance is more likely to have read the docs.

**Comment by daviddarnes** [comment]
It needs some kind of clever bundling method to switch themes, something I think other platforms might take advantage of (Siteleaf, CloudCannon etc).

**Comment by daviddarnes** [comment]
Now that 3.2 is out I decided to test the theme out again and compare it to https://github.com/jekyll/minima (a theme created by the Jekyll team).

Turns out you need quite a few initial files to see things happen, so overall I wasn't that far off! I used their example content to see what mine did, and after a couple of changes I noticed few things:
- I need to document the initial files required to install this theme
- I need it to make content look good even if there is lots of elements missing

I'll be striking up new issues for these and other bits. Thanks a lot @budparr for the feedback.
