### ISSUE TITLE
Add support for separate favicons

### ISSUE THREAD

**Issue by tarragonparagon** [daviddarnes/garth#17]
Currently, the `shortcut-icon` property is mapped to `{{ site.logo }}`, but when said file is an svg, it won't be rendered by most browsers (save Firefox and Safari). For browsers that don't support non-raster favicons, maybe it'd be good to create a separate `{{ site.favicon }}`?

**Comment by daviddarnes** [comment]
Hi @fancyfarfalle. This is a good request, however I'm not sure what the best solution would be for everyone. I want it to be simple. In my other theme, Alembic, I have a favicon include that allows for multiple sizes https://github.com/daviddarnes/alembic/blob/master/_includes/site-favicons.html.
But again this doesn't cater for multiple files. What would you suggest?

In the interim you could always put the files in the root of your project? Most browser should pick it up without the need for meta information.

**Comment by tarragonparagon** [comment]
Hmmm... that's a good point. The thing is, when the favicon is set to `{{ site.logo }}`, the browser just refuses to load it rather than double-checking for my favicon in the site root. You do make a good point, though— it's hard to balance simplicity and customization. My thought was something like this:
```
{% if site.favicon %}
<link rel="shortcut icon" href="{{ site.favicon }}">
{% else %}
<link rel="shortcut icon" href="{{ site.logo }}">
{% endif %}
```
That way, the user can choose a separate favicon, but if they don't, Jekyll will still attempt to render the `{{ site.logo }}` in case either 1) `{{ site.logo }}` is a .png or 2) the client is a browser that supports non-rasterized favicons.

Thoughts?

**Comment by daviddarnes** [comment]
I think that's pretty reasonable. I wasn't sure of the shortcut icon falling back to the site logo but actually this would maintain current behaviour and add an enhancement. I may copy this over to Alembic too as currently it uses a weird gravatar method of including favicons at multiple sizes.

Feel free to make a pull request!

**Comment by tarragonparagon** [comment]
Pull request has been made (see #18 PR)
