### ISSUE TITLE
Cannot customize colors

### ISSUE THREAD

**Issue by leonelgalan** [daviddarnes/garth#19]
I tried to follow the README's instructions:

> If you're just looking to set your own colours copy the [`_colors.scss`](https://github.com/daviddarnes/garth/blob/master/_sass/_colors.scss) file into your project at the same file path (`_sass/_settings.scss`) and change variables however you wish.

Except I used the tagged version of _\_colors.scss_ that matched the version of the gem I installed: _https://raw.githubusercontent.com/daviddarnes/garth/1.0.2/_sass/_colors.scss_ and I called it _\_sass/\_colors.scss_ (Typo in README?)

I still see the Yellow background and garth's original colors.

Here is more info about my environment and a [sample repo](https://github.com/leonelgalan/garth-jekyll-test)

```
ruby 2.4.4p296 (2018-03-28 revision 63013) [x86_64-darwin17]
jekyll-3.7.3
garth-jekyll-theme-1.0.2
```

**Comment by daviddarnes** [comment]
Hi @leonelgalan. You're right, not only is there a typo in the readme but there is also an issue with duplicating files that reside in the `_sass` directory. I've noticed that the only way to make the main styles file point to the newly created ones in your site is by duplicating the main styles itself. Which is kinda annoying as you have to duplicate it into your own project but not change anything, which could cause updating issues.

Try duplicating the `assets/styles.scss` and see if that produces the desired result. You may have to duplicate the `_sass/garth.scss` file too. Thanks for reporting this!

**Comment by leonelgalan** [comment]
Thanks for the pointers, duplicating _assets/styles.scss_ didn't do much. But _\_sass/garth.scss_ and _\_sass/\_colors.scss_ worked. How about this for the README?

> If you're just looking to set your own colours copy [`_sass/garth.scss`](https://github.com/daviddarnes/garth/blob/master/_sass/garth.scss) and [`_sass/_colors.scss`](https://github.com/daviddarnes/garth/blob/master/_sass/_colors.scss) into your project at the same file path (`_sass/`) and change variables however you wish.

**Comment by daviddarnes** [comment]
@leonelgalan so just duplicating `_sass/garth.scss` and `_sass/_colors.scss` worked? No need to copy the main styles file? Interesting 🤔

If that works then that would be a great change! It would be even better if you made a pull request to the README, that way it'll give you proper contributions reference 👍

**Comment by leonelgalan** [comment]
Yes, here is the changes that worked: https://github.com/leonelgalan/garth-jekyll-test/commit/f6eed692c4f344b98d124746a7ab35cf0112ffa6

Give me a couple of days and I'll submit the PR for the README, I'll take the extra time to read it carefully and "deploy" my Jekyll site, to make sure I don't leave something out.
