### ISSUE TITLE
Pagination Enabled but Missing index.html Template

### ISSUE THREAD

**Issue by alirzasahb** [daviddarnes/garth#30]
Hello,

I hope this message finds you well.

I am experiencing an issue with pagination on my blog. I have added jekyll-paginate to the _config.yml file, but I am encountering the following message:

` Pagination: Pagination is enabled, but I couldn't find an index.html page to use as the pagination template. Skipping pagination.`

**Steps to Reproduce:**

1. Add jekyll-paginate in the _config.yml file.
2. Run bundle exec jekyll serve command

**Expected Behavior:** 
The pagination should function correctly and display the paginated content as intended without any error messages relating to missing templates.

**Actual Behavior:** 
The system skips pagination due to the absence of an index.html page.

**Possible Solution:**
-  Add Pagination Section to Default.html

With Many Thanks,
Alireza

**Comment by daviddarnes** [comment]
Hey there! Are you using this theme for your site? If so it’s already got pagination built in. To customise it you either need to edit the `_includes/post-pagination.html` file or, if you’re using it as a theme gem, add that file to overwrite it. Hope this helps!

**Comment by alirzasahb** [comment]
Thanks! Yes, I am using this theme as a Gem file for my GitHub page. Should I create folders according to your description?

**Comment by daviddarnes** [comment]
Yes! It's actually all documented here on the official Jekyll docs https://jekyllrb.com/docs/themes/#overriding-theme-defaults

**Comment by alirzasahb** [comment]
Thanks!

**Comment by alirzasahb** [comment]
Thanks
